services:
  docs:
    image: di치rios_oficiais_alems_local_docs
    container_name: di치rios_oficiais_alems_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./di치rios_oficiais_alems:/app/di치rios_oficiais_alems:z
    ports:
      - '9000:9000'
    command: /start-docs
